### ISSUE TITLE
Feedback on MS report outline - "Testing of a Graph Framework" section

### ISSUE THREAD

**Issue by annielytical** [owensgroup/Robison_MS_Project_Report#1]
The entire report will have two major sections: "Testing of a Graph Framework" and "Programmability of a Graph Framework". So far I have outlined the first in [this outline](https://github.com/annielytical/Robison_MS_Project_Report/blob/e73ff7814cec6620da02674ba2ff8b72cc0032b1/report.pdf).

The main feedback I am hoping to get:
1) Is this in scope for what you expect from an MS report?
2) Do any pertinent topics come to mind that I am missing?

Thank you!

**Comment by jowens** [comment]
Just for searchability reasons, "Testing and Programmability of a GPU Graph Framework" might be preferable.

# Testing

Be explicit in the writeup about your goals. It might be "maximize metrics" and that's OK, but if you have additional/alternate goals, make them explicit.

I like that you are being explicit about methodology. Are these best practices? Where do we differ from best practices? How could we do better?

The most important part of this "results" section is what we learned. Like, you have a ton of plots to draw, but why those plots? What did we learn? For instance, things to possibly learn include:
- scalability across generations of GPUs (are we scaling well?)
- are we making good use of the GPU?
- what limits our performance? does that differ by primitive?
- where has essentials improved over Gunrock? Regressed? Why?
- what metrics are correlated in our implementation, e.g., is MTEPS correlated with edge count or vertex count or degree distribution etc.?
- what datasets are "good" for these implementations and bad, and most importantly, why?

The _why_ on all of these is most important. It is not enough just to say "results show trend X", we have to say "results show trend X and here is why". To do this, I suggest: I have pointed many students to this and respectfully request you read it! https://dl.acm.org/doi/10.1145/3213770

This does not have to be comprehensive in terms of every possible metric. You (and @neoblizz) should discuss which are most important/significant. But the ones you do need to be meaningful and have good explanations.

If "programmability" is well-evaluated as well, this is a fine scope for a MS report.

**Comment by annielytical** [comment]
> Just for searchability reasons, "Testing and Programmability of a GPU Graph Framework" might be preferable.
> # Testing
> 
> Be explicit in the writeup about your goals. It might be "maximize metrics" and that's OK, but if you have additional/alternate goals, make them explicit.
> 
> I like that you are being explicit about methodology. Are these best practices? Where do we differ from best practices? How could we do better?
> 
> The most important part of this "results" section is what we learned. Like, you have a ton of plots to draw, but why those plots? What did we learn? For instance, things to possibly learn include:
> 
>     * scalability across generations of GPUs (are we scaling well?)
> 
>     * are we making good use of the GPU?
> 
>     * what limits our performance? does that differ by primitive?
> 
>     * where has essentials improved over Gunrock? Regressed? Why?
> 
>     * what metrics are correlated in our implementation, e.g., is MTEPS correlated with edge count or vertex count or degree distribution etc.?
> 
>     * what datasets are "good" for these implementations and bad, and most importantly, why?
> 
> 
> The _why_ on all of these is most important. It is not enough just to say "results show trend X", we have to say "results show trend X and here is why". To do this, I suggest: I have pointed many students to this and respectfully request you read it! https://dl.acm.org/doi/10.1145/3213770
> 
> This does not have to be comprehensive in terms of every possible metric. You (and @neoblizz) should discuss which are most important/significant. But the ones you do need to be meaningful and have good explanations.
> 
> If "programmability" is well-evaluated as well, this is a fine scope for a MS report.

This is very helpful feedback. I will make sure to incorporate it. Thank you!
